#!/usr/bin/env python3
"""
Regenerates:
  - track-<id>.html for every entry in tracks.json (one real page per track)
  - tracks-data.js (a plain JS file the homepage reads directly — no fetch(),
    so the grid works even when index.html is opened by double-clicking it)

Run this after you edit tracks.json:
    python3 build.py

That's the only step needed to add a new track: add one entry to
tracks.json, run this script, upload/commit the new files it creates.
"""
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(ROOT, "tracks.json"), encoding="utf-8") as f:
    tracks = json.load(f)

with open(os.path.join(ROOT, "track-template.html"), encoding="utf-8") as f:
    template = f.read()

for t in tracks:
    html = (
        template
        .replace("{{ID}}", t["id"])
        .replace("{{TITLE}}", t["title"])
        .replace("{{DESCRIPTION}}", t["description"])
        .replace("{{VIDEO}}", t["video"])
    )
    out_path = os.path.join(ROOT, f"track-{t['id']}.html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"wrote track-{t['id']}.html")

with open(os.path.join(ROOT, "tracks-data.js"), "w", encoding="utf-8") as f:
    f.write("// Auto-generated by build.py — do not edit by hand.\n")
    f.write("// Edit tracks.json instead, then re-run: python3 build.py\n")
    f.write("var TRACKS = ")
    json.dump(tracks, f, indent=2)
    f.write(";\n")
print("wrote tracks-data.js")

print(f"\nDone — {len(tracks)} track page(s) generated.")
