// Auto-generated by build.py — do not edit by hand.
// Edit tracks.json instead, then re-run: python3 build.py
var TRACKS = [
  {
    "id": "moneytalks",
    "title": "Money Talks",
    "description": "Official visual for Money Talks by hayknz.",
    "video": "moneytalks.mp4",
    "color": "#0f6e56"
  },
  {
    "id": "ayamiatata",
    "title": "Ayamiatata",
    "description": "Official visual for Ayamiatata by hayknz.",
    "video": "Ayamiatata.mp4",
    "color": "#085041"
  },
  {
    "id": "paroparo",
    "title": "Paroparo",
    "description": "Official visual for Paroparo by hayknz.",
    "video": "paroparo.mp4",
    "color": "#3b6d11"
  },
  {
    "id": "streetfight",
    "title": "Street Fight",
    "description": "Official visual for Street Fight by hayknz.",
    "video": "streetfight.mp4",
    "color": "#27500a"
  }
];
